services:
  kafka:
    image: ${KAFKA_IMAGE:-apache/kafka:latest}
    hostname: kafka
    container_name: kafka
    restart: on-failure
    ports:
      - "9094:9094"
      - "9092:9092"
    healthcheck:
      test: [
        "CMD",
        "/opt/kafka/bin/kafka-topics.sh",
        "--list",
        "--bootstrap-server",
        "kafka:9092"
      ]
      start_period: 30s
      interval: 5s
      timeout: 30s
      retries: 10
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: CONTROLLER://:9093,INTERNAL://:9092,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://127.0.0.1:9094,CONTROLLER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka-rest-proxy:
    image: ${KAFKA_REST_IMAGE:-confluentinc/cp-kafka-rest:7.2.1}
    ports:
      - 8082:8082
    container_name: kafka-rest-proxy
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_REST_LISTENERS=http://0.0.0.0:8082
      - KAFKA_REST_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:9092
      - KAFKA_REST_SCHEMA_REGISTRY_URL=http://schemaregistry:8081

  kafka-ui:
    image: ${KAFKA_UI_IMAGE:-provectuslabs/kafka-ui:latest}
    ports:
      - 8080:8080
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://schemaregistry:8081

  schema-registry:
    image: ${SCHEMA_REGISTRY_IMAGE:-confluentinc/cp-schema-registry:7.2.1}
    container_name: schemaregistry
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - 8081:8081
    environment:
      - SCHEMA_REGISTRY_HOST_NAME=schemaregistry
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes

  kafka-init:
    image: ${KAFKA_IMAGE:-apache/kafka:latest}
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/opt/kafka/bin/kafka-topics.sh"]
    command:
      - "--bootstrap-server"
      - "kafka:9092"
      - "--create"
      - "--topic"
      - "generation-request"
      - "--if-not-exists"
    restart: "no"
